services:
    db:
        container_name: checkmarx_postgres_db
        image: postgres:16.3-alpine3.19
        env_file:
            - ../configs/.env
        ports:
            - 5432:5432
        networks:
            - checkmarx
        volumes:
            - checkmarx_postgres_db:/data/db
        restart: always
    adminer:
        container_name: checkmarx_adminer
        image: adminer:4.8.1-standalone
        environment:
            - ADMINER_DEFAULT_SERVER=checkmarx_postgres_db
        networks:
            - checkmarx
        ports:
            - 3333:8080
        restart: always
    # server:
    #     container_name: checkmarx_server
    #     env_file:
    #         - ../configs/.env
    #     depends_on:
    #         - db
    #     build:
    #         context: ../
    #         dockerfile: ./deployments/Dockerfile
    #     ports:
    #         - 8000:8000
    #     networks:
    #         - checkmarx
    #     restart: always
networks:
    checkmarx:
        driver: bridge
        name: checkmarx
volumes:
    checkmarx_postgres_db:
    checkmarx_jaeger:
