services:
    db:
        container_name: checkmarx_postgres_db
        image: postgres:16.3-alpine3.19
        env_file:
            - ../configs/.env
        ports:
            - 5432:5432
        networks:
            - checkmarx
        volumes:
            - checkmarx_postgres_db:/data/db
        restart: always
    # redis:
    #     container_name: checkmarx_redis
    #     image: redis:7.2.5-alpine3.19
    #     env_file:
    #         - ../configs/.env
    #     ports:
    #         - 6379:6379
    #     networks:
    #         - checkmarx
    #     restart: always
    # jaeger:
    #     container_name: checkmarx_jaeger
    #     image: jaegertracing/all-in-one:1.57.0
    #     env_file:
    #         - ../configs/.env
    #     environment:
    #         - COLLECTOR_OTLP_ENABLED=true
    #     ports:
    #         - 4317:4317
    #         - 16686:16686
    #     networks:
    #         - checkmarx
    #     volumes:
    #         - checkmarx_jaeger:/data/jaeger
    #     restart: always
    adminer:
        container_name: checkmarx_adminer
        image: adminer:4.8.1-standalone
        environment:
            - ADMINER_DEFAULT_SERVER=checkmarx_postgres_db
        networks:
            - checkmarx
        ports:
            - 3333:8080
        restart: always
    # server:
    #     container_name: checkmarx_server
    #     env_file:
    #         - ../configs/.env
    #     depends_on:
    #         - db
    #     build:
    #         context: ../
    #         dockerfile: ./deployments/Dockerfile
    #     ports:
    #         - 8000:8000
    #     networks:
    #         - checkmarx
    #     restart: always
networks:
    checkmarx:
        driver: bridge
        name: checkmarx
volumes:
    checkmarx_postgres_db:
    checkmarx_jaeger:
